name = "remix-nextui-cloudflare"
compatibility_date = "2024-02-11"

[vars]
THE_MOVIE_DB_ACCESS_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MTZlOGVhODUzODE5YjZjZDkwZGFjMWQyMWZmY2U4OSIsInN1YiI6IjViZjdlYjMxMGUwYTI2NDMyMDA1NmQ5YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Nzk85iuWIOoJXcT0feUUy8LX9p7YeWLZHQIowueJRPE"